server:
  port: 9095
  servlet:
    context-path: /


spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 12MB

  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_dev
    username: postgres
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    show-sql: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        #format_sql: true
        jdbc:
          time_zone: UTC
#        dialect: org.hibernate.spatial.dialect.postgis.PostgisDialect

  liquibase:
    default-schema: public

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
# spring.jpa.properties.hibernate.dialect=org.hibernate.spatial.dialect.postgis.PostgisDialect
#    serialization:
#      FAIL_ON_EMPTY_BEANS: false

#  kafka:
#    bootstrap-servers: localhost:9092
#    producer:
#      key-serializer:
#        org.apache.kafka.common.serialization.StringSerializer
#      value-serializer:
#        org.apache.kafka.common.serialization.StringSerializer

jwt:
  auth:
    converter:
      resource-id: deliciasapp-auth-client

keycloak:
  use-resource-role-mappings: true
  realm: delicias-app
  domain: 192.168.101.100:9001 # localhost:9001 #192.168.101.16:9001
  adminClientId: admin-cli
  adminClientSecret: PP8mW3FCVO2vbC0dsiJFU6A8czcBokvx
  client: deliciasapp-auth-client
  urls:
    auth: http://${keycloak.domain}

elasticsearch:
  url: 'https://localhost:9200'
  apiKey: 'd1h5ZjI1QUJUX1pPSXB6M2RWdlY6UFRpaWpPN21RcVdWTmh5RmZKc1pnQQ=='

delicias:
  mobileConfigId: 27032024
  production: false
  timezone: -6
#  files:
#    server: 'http://192.168.101.100'
#    resources: ${delicias.files.server}/resources
#    staticDefault: ${delicias.files.server}/resources/delicias-logo.png
#    staticDefault: ${delicias.files.server}/static/dl.png
#    upload:
#      path: '/delicias_cloud'
  supabase:
    domain: 'http://192.168.101.100:8000'
    url: 'http://localhost:8000'
    key: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyAgCiAgICAicm9sZSI6ICJhbm9uIiwKICAgICJpc3MiOiAic3VwYWJhc2UtZGVtbyIsCiAgICAiaWF0IjogMTY0MTc2OTIwMCwKICAgICJleHAiOiAxNzk5NTM1NjAwCn0.dc_X5iR_VP_qT0zsiyj_I_OZ2T9FtRU2BBNWN8Bu4GE'
    bucket: 'delicias'
    logo: ${delicias.supabase.domain}/storage/v1/object/public/delicias/dl.png


google:
  maps:
    api:
      key: AIzaSyBA46_7mzzYeQlV4u-6-763XESq9UDUEC8